services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-habit_tracker}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "3011:3011"
    volumes:
      - session-data:/tmp/sessions
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/habit_tracker
      - PORT=3011
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3011}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3011}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3011}
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  session-data:
  postgres-data:
