services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habit_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: node:20-alpine
    working_dir: /app/backend
    command: sh -c "apk add --no-cache openssl && npm install && npx prisma generate && npm run dev"
    ports:
      - "3011:3011"
    volumes:
      - ./backend:/app/backend
      - ./:/app
      - /app/backend/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/habit_tracker
      PORT: 3011
      CORS_ORIGIN: http://localhost:5174
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: http://localhost:3011/api/auth/google/callback
      FRONTEND_URL: http://localhost:5174
    depends_on:
      - postgres

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      VITE_API_URL: http://localhost:3011
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  postgres-data:
